import {ObjectId} from "mongodb";

export interface EventPbxCentralHistoriesDTO {
    "_id": ObjectId,
    "client_id": string,
    "central_id": string,
    "call_id": string,
    "time": Date,
    "event": string,
    "queue_id": string,
    "queue_name": string,
    "number": string,
    "sequence_id": string,
    "last_sequence": string,
    "parameter0": string,
    "parameter1": string,
    "parameter2": string,
    "parameter3": string,
    "parameter4": string,
    "parameter5": string,
    "parameter6": string,
    "parameter7": string,
    "parameter8": string,
    "parameter9": string,
    "carrier": string,
    "call_id_num": number,
    "sequence_id_num": number,
}
